export TERM=xterm
export RPROMPT='[%~]'
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
export EDITOR=vi
export PAGER=less
export LC_ALL=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export MAKEFLAGS="-j 20"
export PATH=$PATH:$HOME/.cargo/bin
export RUSTFLAGS="-C target-feature=+strict-align"
