setopt auto_menu auto_cd correct auto_name_dirs auto_remove_slash
setopt extended_history inc_append_history hist_ignore_dups hist_ignore_space prompt_subst share_history
setopt pushd_ignore_dups rm_star_silent sun_keyboard_hack
setopt extended_glob list_types no_beep always_last_prompt
setopt cdable_vars auto_param_keys magic_equal_subst sh_wordsplit
setopt auto_pushd complete_aliases
set convert-meta off
set meta-flag on
set output-meta on
set input-meta on
set kanji-code utf-8

unsetopt beep

alias ls='ls -F --color'
alias la='ls -Fa --color'
alias ll='ls -Fal --color'
alias l.='ls -Fa --color .[a-zA-Z0-9]*'

autoload -U compinit
compinit

bindkey -e

# set terminal title including current directory
#
case "${TERM}" in
kterm*|xterm)
precmd() {
echo -ne "\033]0;${USER}@${HOST%%.*}:${PWD}\007"
}
;;
esac

autoload -Uz vcs_info

zstyle ':vcs_info:*' formats '[%b]'
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () {
psvar=()
LANG=en_US.UTF-8 vcs_info
[[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
}

# show git's version
export PROMPT="%n@%m %1(v|%F%1v%f |)%#> "

source $HOME/.cargo/env
